### ISSUE TITLE
Cartões da Dashboard [15 pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/bookshelf_v1#5]
Implementação de conteúdos dos cartões da dashboard. Montar um sistema de coleções que responda ao conteúdo de cartões adicionados ao feed de notícias de cada usuário.

**Comment by victoricoma** [comment]
Vamos fazer um arquivo em assets .json para emular a entrega de uma API do back-end depois vamos migrar a interface para dentro do componente alterando o serviço e sua apresentação em scss e html.

**Comment by jrcodev** [comment]
Deu um erro no ng serve:
 reason: SyntaxError: JSON5: invalid character ',' at 1:133
    at syntaxError (D:\Files\Documentos\Soulcode\Angular\filmflix-angular-v2\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (D:\Files\Documentos\Soulcode\Angular\filmflix-angular-v2\node_modules\json5\lib\parse.js:1028:12)
